app:
  image: yujilow1220/note-server
  restart: always
  links:
    - notedb
    - redmine
  environment:
    - TODO_HOST=redmine
    - TODO_USERNAME=headless
    - TODO_PASSWORD=headless
    - TODO_APIKEY=d4a9a37be3bd2202f5a31389f2ca25d249221399
  volumes:
    - .:/usr/src/app
  ports:
    - 3030:3000

notedb:
   image: mongo
   ports:
    - 27107:27107
   volumes:
    - /Users/owner/dev/utils/docker/wekan/data:/data/db

redmine:
  image: redmine
  ports:
    - 8080:3000
  environment:
    REDMINE_DB_MYSQL: db
    REDMINE_DB_PASSWORD: example
  links:
    - db
  restart: always
  volumes:
    - ./redmine/data:/usr/src/redmine/files

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: redmine
  restart: always
